### ISSUE TITLE
Assertion failure on cunumeric.mean

### ISSUE THREAD

**Issue by manopapad** [nv-legate/cunumeric#1041]
The following test file:

```
import cunumeric as num
arr_num = num.ones(shape=(4,))
res_num = num.mean(arr_num)
```

fails on latest legion/legate.core/cunumeric with:

```
> LEGATE_TEST=1 legate --gpus 1 b.py
legion_python: /home/mpapadakis/a/legion/runtime/legion/runtime.cc:1004: const void* Legion::Internal::FutureImpl::get_buffer(Legion::Processor, Realm::Memory::Kind, size_t*, bool, bool, const char*): Assertion `proc.exists() || (memkind == runtime->runtime_system_memory.kind())' failed.
Signal 6 received by node 0, process 1539947 (thread 7f7001948000) - obtaining backtrace
Signal 6 received by process 1539947 (thread 7f7001948000) at: stack trace: 29 frames
  [0] = unknown symbol at unknown file:0 [00007f701204251f]
  [1] = pthread_kill@@GLIBC_2.34 at ./nptl/pthread_kill.c:44 [00007f7012096a7c]
  [2] = raise at ../sysdeps/posix/raise.c:26 [00007f7012042475]
  [3] = abort at ./stdlib/abort.c:79 [00007f70120287f2]
  [4] = __assert_fail_base.cold at ./assert/assert.c:92 [00007f701202871a]
  [5] = __assert_fail at ./assert/assert.c:101 [00007f7012039e95]
  [6] = Legion::Internal::FutureImpl::get_buffer(Realm::Processor, Realm::Memory::Kind, unsigned long*, bool, bool, char const*) at /home/mpapadakis/a/legion/runtime/legion/runtime.cc:1004 [00007f7016b0898d]
  [7] = Legion::Future::get_buffer(Realm::Memory::Kind, unsigned long*, bool, bool, char const*) const at /home/mpapadakis/a/legion/runtime/legion/legion.cc:2432 [00007f7016662bfe]
  [8] = legate::FutureWrapper::FutureWrapper(bool, unsigned int, Legion::Domain, Legion::Future, bool) at /home/mpapadakis/a/legate.core/src/core/data/store.cc:149 [00007f6fececb8c8]
  [9] = legate::TaskDeserializer::_unpack(legate::FutureWrapper&) at /home/mpapadakis/a/legate.core/src/core/utilities/deserializer.cc:82 [00007f6fed0649f5]
  [10] = legate::FutureWrapper legate::BaseDeserializer<legate::TaskDeserializer>::unpack<legate::FutureWrapper>() at /home/mpapadakis/a/legate.core/src/core/utilities/deserializer.h:45 [00007f6fed066960]
  [11] = legate::TaskDeserializer::_unpack(legate::Store&) at /home/mpapadakis/a/legate.core/src/core/utilities/deserializer.cc:51 [00007f6fed0643de]
  [12] = legate::Store legate::BaseDeserializer<legate::TaskDeserializer>::unpack<legate::Store>() at /home/mpapadakis/a/legate.core/src/core/utilities/deserializer.h:45 [00007f6fecf3fd9e]
  [13] = void legate::BaseDeserializer<legate::TaskDeserializer>::_unpack<legate::Store>(std::vector<legate::Store, std::allocator<legate::Store> >&) at /home/mpapadakis/a/legate.core/src/core/utilities/deserializer.h:63 [00007f6fecf3ecc8]
  [14] = std::vector<legate::Store, std::allocator<legate::Store> > legate::BaseDeserializer<legate::TaskDeserializer>::unpack<std::vector<legate::Store, std::allocator<legate::Store> > >() at /home/mpapadakis/a/legate.core/src/core/utilities/deserializer.h:45 [00007f6fecf3dcf2]
  [15] = legate::TaskContext::TaskContext(Legion::Task const*, std::vector<Legion::PhysicalRegion, std::allocator<Legion::PhysicalRegion> > const&, Legion::Internal::TaskContext*, Legion::Runtime*) at /home/mpapadakis/a/legate.core/src/core/runtime/context.cc:187 [00007f6fecf3bd11]
  [16] = legate::detail::task_wrapper(void (*)(legate::TaskContext&), std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, void const*, unsigned long, void const*, unsigned long, Realm::Processor) at /home/mpapadakis/a/legate.core/src/core/task/task.cc:71 [00007f6fecf60c9e]
  [17] = void legate::LegateTask<cunumeric::ScalarUnaryRedTask>::legate_task_wrapper<&cunumeric::ScalarUnaryRedTask::gpu_variant>(void const*, unsigned long, void const*, unsigned long, Realm::Processor) at /home/mpapadakis/a/legate.core/src/core/task/task.inl:37 [00007f6d6c519c39]
  [18] = Realm::Cuda::GPUProcessor::execute_task(unsigned int, Realm::ByteArrayRef const&) at /home/mpapadakis/a/legion/runtime/realm/cuda/cuda_module.cc:2152 [00007f7012fcb71f]
  [19] = Realm::Task::execute_on_processor(Realm::Processor) at /home/mpapadakis/a/legion/runtime/realm/tasks.cc:326 [00007f7012f8fe70]
  [20] = Realm::KernelThreadTaskScheduler::execute_task(Realm::Task*) at /home/mpapadakis/a/legion/runtime/realm/tasks.cc:1421 [00007f7012f94317]
  [21] = Realm::Cuda::GPUTaskScheduler<Realm::KernelThreadTaskScheduler>::execute_task(Realm::Task*) at /home/mpapadakis/a/legion/runtime/realm/cuda/cuda_module.cc:1537 [00007f7012ff61c5]
  [22] = Realm::ThreadedTaskScheduler::scheduler_loop() at /home/mpapadakis/a/legion/runtime/realm/tasks.cc:1160 [00007f7012f93010]
  [23] = Realm::ThreadedTaskScheduler::scheduler_loop_wlock() at /home/mpapadakis/a/legion/runtime/realm/tasks.cc:1272 [00007f7012f93678]
  [24] = void Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop_wlock>(void*) at /home/mpapadakis/a/legion/runtime/realm/threads.inl:97 [00007f7012f9b423]
  [25] = Realm::KernelThread::pthread_entry(void*) at /home/mpapadakis/a/legion/runtime/realm/threads.cc:781 [00007f7012fa8140]
  [26] = start_thread at ./nptl/pthread_create.c:442 [00007f7012094b42]
  [27] = __clone3 at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81 [00007f70121269ff]
  [28] = unknown symbol at unknown file:0 [ffffffffffffffff]
```

**Comment by magnatelee** [comment]
@manopapad do you mind print the `proc` and `memkind` you're seeing in frame 6? `proc` should exist in this case, so the assertion shouldn't hit the second condition.

**Comment by manopapad** [comment]
The Future buffer is being requested on zero-copy memory:

```
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140736959635456) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140736959635456) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140736959635456, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff1e42476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff1e287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff1e2871b in __assert_fail_base (fmt=0x7ffff1fdd150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=0x7ffff7406518 "proc.exists() || (memkind == runtime->runtime_system_memory.kind())", file=0x7ffff7405940 "/home/mpapadakis/a/legion/runtime/legion/runtime.cc", line=1007, function=<optimized out>) at ./assert/assert.c:92
#6  0x00007ffff1e39e96 in __GI___assert_fail (assertion=0x7ffff7406518 "proc.exists() || (memkind == runtime->runtime_system_memory.kind())", file=0x7ffff7405940 "/home/mpapadakis/a/legion/runtime/legion/runtime.cc", line=1007, function=0x7ffff7406498 "const void* Legion::Internal::FutureImpl::get_buffer(Legion::Processor, Realm::Memory::Kind, size_t*, bool, bool, const char*)") at ./assert/assert.c:101
#7  0x00007ffff6908a3b in Legion::Internal::FutureImpl::get_buffer (this=0x7ffda0795960, proc=..., memkind=Realm::Memory::Z_COPY_MEM, extent_in_bytes=0x0, check_extent=false, silence_warnings=false, warning_string=0x0) at /home/mpapadakis/a/legion/runtime/legion/runtime.cc:1007
#8  0x00007ffff6462c1f in Legion::Future::get_buffer (this=0x7fffe07c1538, memory=Realm::Memory::Z_COPY_MEM, extent_in_bytes=0x0, check_size=false, silence_warnings=false, warning_string=0x0) at /home/mpapadakis/a/legion/runtime/legion/legion.cc:2432
#9  0x00007ffec1ccb8c9 in legate::FutureWrapper::FutureWrapper (this=0x7fffe07c14e0, read_only=false, field_size=8, domain=..., future=..., initialize=true) at /home/mpapadakis/a/legate.core/src/core/data/store.cc:149
#10 0x00007ffec1e649f6 in legate::TaskDeserializer::_unpack (this=0x7fffe07c1d40, value=...) at /home/mpapadakis/a/legate.core/src/core/utilities/deserializer.cc:82
#11 0x00007ffec1e66961 in legate::BaseDeserializer<legate::TaskDeserializer>::unpack<legate::FutureWrapper> (this=0x7fffe07c1d40) at /home/mpapadakis/a/legate.core/src/core/utilities/deserializer.h:45
#12 0x00007ffec1e643df in legate::TaskDeserializer::_unpack (this=0x7fffe07c1d40, value=...) at /home/mpapadakis/a/legate.core/src/core/utilities/deserializer.cc:51
#13 0x00007ffec1d3fd9f in legate::BaseDeserializer<legate::TaskDeserializer>::unpack<legate::Store> (this=0x7fffe07c1d40) at /home/mpapadakis/a/legate.core/src/core/utilities/deserializer.h:45
#14 0x00007ffec1d3ecc9 in legate::BaseDeserializer<legate::TaskDeserializer>::_unpack<legate::Store> (this=0x7fffe07c1d40, values=...) at /home/mpapadakis/a/legate.core/src/core/utilities/deserializer.h:63
#15 0x00007ffec1d3dcf3 in legate::BaseDeserializer<legate::TaskDeserializer>::unpack<std::vector<legate::Store, std::allocator<legate::Store> > > (this=0x7fffe07c1d40) at /home/mpapadakis/a/legate.core/src/core/utilities/deserializer.h:45
#16 0x00007ffec1d3bd12 in legate::TaskContext::TaskContext (this=0x7fffe07c1e70, task=0x7ffda0164790, regions=..., context=0x7ffd7c04eb00, runtime=0x555555f7c540) at /home/mpapadakis/a/legate.core/src/core/runtime/context.cc:187
#17 0x00007ffec1d60c9f in legate::detail::task_wrapper (variant_impl=0x7ffd4e48687a <cunumeric::ScalarUnaryRedTask::gpu_variant(legate::TaskContext&)>, task_name=..., args=0x7ffda0839980, arglen=8, userdata=0x0, userlen=0, p=...) at /home/mpapadakis/a/legate.core/src/core/task/task.cc:71
#18 0x00007ffd4c519c3a in legate::LegateTask<cunumeric::ScalarUnaryRedTask>::legate_task_wrapper<&cunumeric::ScalarUnaryRedTask::gpu_variant> (args=0x7ffda0839980, arglen=8, userdata=0x0, userlen=0, p=...) at /home/mpapadakis/a/legate.core/src/core/task/task.inl:37
#19 0x00007ffff2dcb720 in Realm::Cuda::GPUProcessor::execute_task (this=0x555555f79720, func_id=46, task_args=...) at /home/mpapadakis/a/legion/runtime/realm/cuda/cuda_module.cc:2152
#20 0x00007ffff2d8fe71 in Realm::Task::execute_on_processor (this=0x7ffda0839800, p=...) at /home/mpapadakis/a/legion/runtime/realm/tasks.cc:326
#21 0x00007ffff2d94318 in Realm::KernelThreadTaskScheduler::execute_task (this=0x555555f79d80, task=0x7ffda0839800) at /home/mpapadakis/a/legion/runtime/realm/tasks.cc:1421
#22 0x00007ffff2df61c6 in Realm::Cuda::GPUTaskScheduler<Realm::KernelThreadTaskScheduler>::execute_task (this=0x555555f79d80, task=0x7ffda0839800) at /home/mpapadakis/a/legion/runtime/realm/cuda/cuda_module.cc:1537
#23 0x00007ffff2d93011 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x555555f79d80) at /home/mpapadakis/a/legion/runtime/realm/tasks.cc:1160
#24 0x00007ffff2d93679 in Realm::ThreadedTaskScheduler::scheduler_loop_wlock (this=0x555555f79d80) at /home/mpapadakis/a/legion/runtime/realm/tasks.cc:1272
#25 0x00007ffff2d9b424 in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop_wlock> (obj=0x555555f79d80) at /home/mpapadakis/a/legion/runtime/realm/threads.inl:97
#26 0x00007ffff2da8141 in Realm::KernelThread::pthread_entry (data=0x55555616d790) at /home/mpapadakis/a/legion/runtime/realm/threads.cc:781
#27 0x00007ffff1e94b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#28 0x00007ffff1f26a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by lightsighter** [comment]
Hmm, ok, I will try to push a fix later today.

**Comment by manopapad** [comment]
@lightsighter you added this assertion with https://gitlab.com/StanfordLegion/legion/-/commit/86b90ae285405a382b808e1575cc72bf62968cf1. Should we not be instantiating Future buffers on zero-copy memory?

**Comment by lightsighter** [comment]
I really regret giving anyone the ability to map futures anywhere other than system memory, but the interface should support this case.

**Comment by lightsighter** [comment]
@manopapad Try with this commit: https://gitlab.com/StanfordLegion/legion/-/commit/39e94b201e3f247f985a63bee497db880288d94c

**Comment by manopapad** [comment]
That fixed it!
