### ISSUE TITLE
Error when reshape command is run with 2 cpus

### ISSUE THREAD

**Issue by darshancr** [nv-legate/cunumeric#1060]
Command - array = np.reshape(J,(100)), When run with 2 cpus

Error - legate.core.transform.NonInvertibleError legion_python:
/data/home/sandeepd/Misc/miniconda3/envs/rel-legate/conda-bld/legate-core_1690202006257/work/build/_deps/legio
n-src/runtime/realm/python/python_module.cc:1009: virtual void
Realm::LocalPythonProcessor::execute_task(Realm::Processor::TaskFuncID, const Realm::ByteArrayRef&): Assertion `0'
failed.

Signal 6 received by node 0, process 2956 (thread 7fdae8788c00) - obtaining backtrace

Signal 6 received by process 2956 (thread 7fdae8788c00) at: stack trace: 15 frames

Complete error - https://drive.google.com/file/d/1GiR3CwpxIuf_6iu5X-HgCZ_hnkmEBUL6/view

**Comment by manopapad** [comment]
Thanks for reporting this! Unfortunately I was not able to reproduce this with this simple program:

```
import cunumeric as cn
J = cn.ones((5,10))
d = cn.reshape(J[:,2:4], 10)
```

Can you please share the version of legate.core and cunumeric you're using, and ideally a small reproducer?

**Comment by JayaghoshH** [comment]
It works for smaller matrix
But when matrix (J) is of order 2000*2 and reshaped into array of order 4000, it's showing this error

**Comment by manopapad** [comment]
I am still unable to reproduce, using this program:

```
import cunumeric as cn
J = cn.ones((2000, 2))
d = cn.reshape(J, (4000,))
```

and running as follows:

```
legate --cpus 2 c.py
```

Can you please provide a full program that triggers this issue, and share the version of legate.core and cunumeric that you're using (`legate --version`)?

**Comment by JayaghoshH** [comment]
import cunumeric as np
A=np.ones((50000,4))
c = np.reshape(A[:,0:2],(100000))              # Reshaping it into a matrix
d = np.reshape(A[:,2:4],(100000))
A = np.array((c,d))
print(np.max(A))
               

Try running this with multiple cpus
I am getting same error as mentioned above

**Comment by manopapad** [comment]
Thanks, I was able to reproduce. CC @magnatelee to take a further look

This fails for me:

```
import cunumeric as cn
A = cn.ones((50000,4))
x = A[:,2:4]
x.reshape((100000,))
```

with the following output:

```
~/cunumeric> legate --cpus 2 a.py
[0 - 7ff859bfce80]    0.000225 {4}{threads}: reservation ('CPU proc 1d00000000000003') cannot be satisfied
[0 - 700001860000]    2.305067 {6}{python}: python exception occurred within task:
Traceback (most recent call last):
  File "/Users/mpapadakis/legion/bindings/python/build/lib/legion_top.py", line 475, in legion_python_main
    run_path(args[start], '__main__')
  File "/Users/mpapadakis/legion/bindings/python/build/lib/legion_top.py", line 295, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "a.py", line 27, in <module>
    x.reshape((100000,))
  File "/Users/mpapadakis/legate.core/legate/core/runtime.py", line 2149, in wrapper
    result = func(*args, **kwargs)
  File "/Users/mpapadakis/cunumeric/cunumeric/coverage.py", line 120, in wrapper
    return func(*args, **kwargs)
  File "/Users/mpapadakis/cunumeric/cunumeric/array.py", line 3493, in reshape
    thunk=self._thunk.reshape(computed_shape, order),
  File "/Users/mpapadakis/cunumeric/cunumeric/deferred.py", line 1257, in reshape
    tgt_array.copy(src_array, deep=True)
  File "/Users/mpapadakis/cunumeric/cunumeric/deferred.py", line 129, in wrapper
    return func(*args, **kwargs)
  File "/Users/mpapadakis/cunumeric/cunumeric/deferred.py", line 392, in copy
    self.unary_op(
  File "/Users/mpapadakis/cunumeric/cunumeric/deferred.py", line 129, in wrapper
    return func(*args, **kwargs)
  File "/Users/mpapadakis/cunumeric/cunumeric/deferred.py", line 3130, in unary_op
    task.execute()
  File "/Users/mpapadakis/legate.core/legate/core/operation.py", line 252, in execute
    runtime.submit(self)
  File "/Users/mpapadakis/legate.core/legate/core/runtime.py", line 1409, in submit
    self.flush_scheduling_window()
  File "/Users/mpapadakis/legate.core/legate/core/runtime.py", line 1402, in flush_scheduling_window
    self._schedule(ops)
  File "/Users/mpapadakis/legate.core/legate/core/runtime.py", line 1395, in _schedule
    op.launch(strategy)
  File "/Users/mpapadakis/legate.core/legate/core/operation.py", line 843, in launch
    req, tag, store_part = self.get_requirement(
  File "/Users/mpapadakis/legate.core/legate/core/operation.py", line 673, in get_requirement
    store_part = store.partition(strategy.get_partition(part_symb))
  File "/Users/mpapadakis/legate.core/legate/core/store.py", line 1708, in partition
    self.invert_partition(partition),
  File "/Users/mpapadakis/legate.core/legate/core/store.py", line 1127, in invert_partition
    return self._transform.invert_partition(partition)
  File "/Users/mpapadakis/legate.core/legate/core/transform.py", line 648, in invert_partition
    self._transform.invert(partition)
  File "/Users/mpapadakis/legate.core/legate/core/transform.py", line 517, in invert
    raise NonInvertibleError()
legate.core.transform.NonInvertibleError
```
