### ISSUE TITLE
"where" fails with IndexError

### ISSUE THREAD

**Issue by suranap** [nv-legate/cunumeric#1065]
https://github.com/nv-legate/cunumeric/blob/2666c08bbdb2ad5f83876ac8ed5c61bbe01af712/cunumeric/eager.py#L1618

```
Welcome to Legion Python interactive console
>>> import cunumeric
>>> import numpy
>>> cunumeric.where(2,1,1)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/auser/mambaforge/envs/legate/lib/python3.1/site-packages/legate/core/runtime.py", line 2149, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/auser/mambaforge/envs/legate/lib/python3.1/site-packages/cunumeric/coverage.py", line 120, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/auser/mambaforge/envs/legate/lib/python3.1/site-packages/cunumeric/array.py", line 148, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/auser/mambaforge/envs/legate/lib/python3.1/site-packages/cunumeric/module.py", line 2995, in where
    return ndarray._perform_where(a, x, y)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/auser/mambaforge/envs/legate/lib/python3.1/site-packages/cunumeric/array.py", line 4386, in _perform_where
    out._thunk.where(mask._thunk, one._thunk, two._thunk)
  File "/home/auser/mambaforge/envs/legate/lib/python3.1/site-packages/cunumeric/eager.py", line 1618, in where
    self.array[:] = np.where(rhs1.array, rhs2.array, rhs3.array)
    ~~~~~~~~~~^^^
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
>>> numpy.where(2,1,1)
array(1)
>>>
```

**Comment by manopapad** [comment]
Thanks for reporting this! This should be fixed with #1067
