### ISSUE TITLE
[BUG] Einstein summation errors when bool passed to 'optimize' arg

### ISSUE THREAD

**Issue by RAMitchell** [nv-legate/cunumeric#1069]
### Software versions

.

### Expected behavior

.

### Observed behavior

.

### Example code or instructions

```Python
import cunumeric as cn

w = cn.zeros(10)
cn.einsum('i->i', w, optimize=True)
```

### Stack traceback or browser console output
[0 - 7f8f6183b000]    1.896067 {6}{python}: python exception occurred within task:
Traceback (most recent call last):
  File "/home/nfs/rorym/anaconda3/envs/legate-test/lib/python3.10/site-packages/legion_top.py", line 475, in legion_python_main
    run_path(args[start], '__main__')
  File "/home/nfs/rorym/anaconda3/envs/legate-test/lib/python3.10/site-packages/legion_top.py", line 295, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "random_experiments/einsum_repro.py", line 4, in <module>
    cn.einsum('i->i', w, optimize=True)
  File "/home/nfs/rorym/anaconda3/envs/legate-test/lib/python3.10/site-packages/legate/core/runtime.py", line 2153, in wrapper
    result = func(*args, **kwargs)
  File "/home/nfs/rorym/anaconda3/envs/legate-test/lib/python3.10/site-packages/cunumeric/coverage.py", line 119, in wrapper
    return func(*args, **kwargs)
  File "/home/nfs/rorym/anaconda3/envs/legate-test/lib/python3.10/site-packages/cunumeric/module.py", line 4665, in einsum
    computed_operands, contractions = oe.contract_path(
  File "/home/nfs/rorym/anaconda3/envs/legate-test/lib/python3.10/site-packages/opt_einsum/contract.py", line 276, in contract_path
    for cnum, contract_inds in enumerate(path):
TypeError: 'bool' object is not iterable

**Comment by manopapad** [comment]
Fixed by https://github.com/nv-legate/cunumeric/pull/1072
