### ISSUE TITLE
[BUG] myarr[np.newaxis] = 1 raises KeyError

### ISSUE THREAD

**Issue by suranap** [nv-legate/cunumeric#1079]
### Software versions

Python      :  3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:40:35) [GCC 12.3.0]
Platform    :  Linux-5.4.0-155-generic-x86_64-with-glibc2.31
Legion      :  v23.11.00.dev-22-ga562200
Legate      :  23.11.00.dev+22.ga562200
Cunumeric   :  23.11.00.dev+10.g586a005a.dirty
Numpy       :  1.24.4
Scipy       :  1.11.3
Numba       :  0.57.1
CTK package :  cuda-version-11.7-h67201e3_2 (conda-forge)
GPU driver  :  535.54.03
GPU devices :
  GPU 0: Tesla P100-SXM2-16GB
  GPU 1: Tesla P100-SXM2-16GB
  GPU 2: Tesla P100-SXM2-16GB
  GPU 3: Tesla P100-SXM2-16GB

### Expected behavior

```
>>> import numpy as np
>>> works = np.array((4,))
>>> works[np.newaxis] = 1
>>> works
array([1])
>>> works.shape
(1,)
```

### Observed behavior

```
>>> import cunumeric as cnp
>>> breaks = cnp.array((4,))
>>> breaks[cnp.newaxis] = 1
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File ".../mambaforge/envs/legate/lib/python3.1/site-packages/legate/core/runtime.py", line 2149, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File ".../projects/legate/cunumeric/cunumeric/coverage.py", line 120, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File ".../projects/legate/cunumeric/cunumeric/array.py", line 148, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File ".../projects/legate/cunumeric/cunumeric/array.py", line 1677, in __setitem__
    raise KeyError("invalid key passed to cunumeric.ndarray")
KeyError: 'invalid key passed to cunumeric.ndarray'
```

### Example code or instructions

```Python
import cunumeric as cnp
breaks = cnp.array((4,))
breaks[cnp.newaxis] = 1
```

### Stack traceback or browser console output

[Numpy newaxis docs](https://numpy.org/doc/stable/reference/constants.html#numpy.newaxis).

**Comment by manopapad** [comment]
@seberg is this expected NumPy behavior?

**Comment by seberg** [comment]
Right, when there are additional dimensions, it is always implicitly the same as adding a `...`, as in `x[newaxis, ...]`.
A `newaxis` doesn't count there (it doesn't index any dimension), so there is one additional dimension here.  So for 1-D it is indeed equivalent.
