### ISSUE TITLE
TypeError while reshape a cunumeric array

### ISSUE THREAD

**Issue by Saran-nns** [nv-legate/cunumeric#127]
I tried to reshape an array and received a type error as below;

Sample code:

``` 
import cunumeric as np
x = np.random.rand(1,10)
x.reshape(10,1) 
```

Throws:

```
Traceback (most recent call last):
  File "/lib/python3.9/site-packages/legion_top.py", line 410, in legion_python_main
    run_path(args[start], run_name='__main__')
  File "/lib/python3.9/site-packages/legion_top.py", line 234, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "test.py", line 5, in <module>
    inputs.reshape(10,1)
  File "/lib/python3.9/site-packages/cunumeric/array.py", line 1368, in reshape
    thunk=self._thunk.reshape(
  File "/lib/python3.9/site-packages/cunumeric/eager.py", line 239, in reshape
    child = self.array.reshape(newshape, order=order)
TypeError: order must be str, not int

```

**Comment by magnatelee** [comment]
Thank you for reporting this! Yeah this is definitely a bug. While we're fixing it, can you try this command instead?
```
x.reshape((10, 1))
```

**Comment by Saran-nns** [comment]
```x.reshape((10, 1))``` works fine. Thanks

**Comment by manopapad** [comment]
This works as expected now.
