### ISSUE TITLE
install.py jetson-nano error

### ISSUE THREAD

**Issue by milwd** [nv-legate/cunumeric#131]
Greetings, trying to install cuNumerics on jetson nano (CUDA arch-5.3 and version-10.2.3). I have pre-installed legate.core and I have got g++.
I tried to install from source using file: install.py

sudo python3 install.py --prefix /usr/local/cunumeric/ --with-core /usr/local/legate/

but I'm getting this :

9 errors detected in the compilation of "/tmp/tmpxft_0000729f_00000000-6_bincount.cpp1.ii".
/usr/local/legate/share/legate/legate.mk:205: recipe for target 'cunumeric/stat/bincount.cu.o' failed
make: * [cunumeric/stat/bincount.cu.o] Error 1
make: * Waiting for unfinished jobs....
Traceback (most recent call last):
  File "install.py", line 495, in <module>
    driver()
  File "install.py", line 491, in driver
    install_cunumeric(unknown=unknown, **vars(args))
  File "install.py", line 387, in install_cunumeric
    unknown,
  File "install.py", line 255, in build_cunumeric
    verbose=verbose,
  File "install.py", line 84, in execute_command
    subprocess.check_call(args, cwd=cwd, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'LEGATE_DIR=/usr/local/legate', 'OPEN_BLAS_DIR=/usr/lib/aarch64-linux-gnu/openblas', 'DEBUG=0', 'DEBUG_RELEASE=0', 'CHECK_BOUNDS=0', 'PREFIX=/usr/local/legate', 'OPENBLAS_FLAGS = -L/usr/lib/aarch64-linux-gnu/openblas/lib -lopenblas -Wl,-rpath,/usr/lib/aarch64-linux-gnu/openblas/lib', '-j', '4', 'install']' returned non-zero exit status 2.

**Comment by manopapad** [comment]
What are the 9 errors detected in the compilation of "/tmp/tmpxft_0000729f_00000000-6_bincount.cpp1.ii"?

**Comment by milwd** [comment]
Hello again, Apologies for the delay, the device wasn't available.
I watched over the process all the way this time. There is a problem with "bincount", idk what.
but here's the whole message: (Thanks in advance)

... compile messages ...
/usr/local/cuda-10/bin/nvcc -o cunumeric/stat/bincount.cu.o -c cunumeric/stat/bincount.cu  -I/usr/local/legate/thrust  -I. -Wno-deprecated-declarations -std=c++14 --expt-relaxed-constexpr --expt-extended-lambda -ccbin=g++ -I/usr/local/legate/include -O2 -DMAXWELL_ARCH -gencode arch=compute_52,code=sm_52 -DLEGATE_USE_CUDA -I/usr/local/cuda-10/include --compiler-options '-fPIC'

cunumeric/stat/bincount.cu(75): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, const double)
          detected during:
            instantiation of "void cunumeric::_weighted_bincount(double *, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)0>]" 
(130): here
            instantiation of "void cunumeric::weighted_bincount_kernel_rd(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)0>]" 
(209): here
            instantiation of "void cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::operator()(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, const legate::AccessorRO<cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::VAL, 1, Legion::coord_t> &, const legate::AccessorRO<double, 1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &) const [with CODE=(legate::LegateTypeCode)0]" 
./cunumeric/stat/bincount_template.inl(41): here
            instantiation of "void cunumeric::BincountImpl<KIND>::operator()<CODE,<unnamed>>(cunumeric::BincountArgs &) const [with KIND=cunumeric::VariantKind::GPU, CODE=BOOL_LT, <unnamed>=(void *)nullptr]" 
./cunumeric/stat/bincount_template.inl(62): here
            instantiation of "void cunumeric::bincount_template<KIND>(legate::TaskContext &) [with KIND=cunumeric::VariantKind::GPU]" 
(238): here

cunumeric/stat/bincount.cu(75): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, const double)
          detected during:
            instantiation of "void cunumeric::_weighted_bincount(double *, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)1>]" 
(130): here
            instantiation of "void cunumeric::weighted_bincount_kernel_rd(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)1>]" 
(209): here
            instantiation of "void cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::operator()(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, const legate::AccessorRO<cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::VAL, 1, Legion::coord_t> &, const legate::AccessorRO<double, 1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &) const [with CODE=(legate::LegateTypeCode)1]" 
./cunumeric/stat/bincount_template.inl(41): here
            instantiation of "void cunumeric::BincountImpl<KIND>::operator()<CODE,<unnamed>>(cunumeric::BincountArgs &) const [with KIND=cunumeric::VariantKind::GPU, CODE=INT8_LT, <unnamed>=(void *)nullptr]" 
./cunumeric/stat/bincount_template.inl(62): here
            instantiation of "void cunumeric::bincount_template<KIND>(legate::TaskContext &) [with KIND=cunumeric::VariantKind::GPU]" 
(238): here

cunumeric/stat/bincount.cu(75): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, const double)
          detected during:
            instantiation of "void cunumeric::_weighted_bincount(double *, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)2>]" 
(130): here
            instantiation of "void cunumeric::weighted_bincount_kernel_rd(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)2>]" 
(209): here
            instantiation of "void cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::operator()(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, const legate::AccessorRO<cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::VAL, 1, Legion::coord_t> &, const legate::AccessorRO<double, 1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &) const [with CODE=(legate::LegateTypeCode)2]" 
./cunumeric/stat/bincount_template.inl(41): here
            instantiation of "void cunumeric::BincountImpl<KIND>::operator()<CODE,<unnamed>>(cunumeric::BincountArgs &) const [with KIND=cunumeric::VariantKind::GPU, CODE=INT16_LT, <unnamed>=(void *)nullptr]" 
./cunumeric/stat/bincount_template.inl(62): here
            instantiation of "void cunumeric::bincount_template<KIND>(legate::TaskContext &) [with KIND=cunumeric::VariantKind::GPU]" 
(238): here

cunumeric/stat/bincount.cu(75): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, const double)
          detected during:
            instantiation of "void cunumeric::_weighted_bincount(double *, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)3>]" 
(130): here
            instantiation of "void cunumeric::weighted_bincount_kernel_rd(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)3>]" 
(209): here
            instantiation of "void cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::operator()(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, const legate::AccessorRO<cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::VAL, 1, Legion::coord_t> &, const legate::AccessorRO<double, 1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &) const [with CODE=(legate::LegateTypeCode)3]" 
./cunumeric/stat/bincount_template.inl(41): here
            instantiation of "void cunumeric::BincountImpl<KIND>::operator()<CODE,<unnamed>>(cunumeric::BincountArgs &) const [with KIND=cunumeric::VariantKind::GPU, CODE=INT32_LT, <unnamed>=(void *)nullptr]" 
./cunumeric/stat/bincount_template.inl(62): here
            instantiation of "void cunumeric::bincount_template<KIND>(legate::TaskContext &) [with KIND=cunumeric::VariantKind::GPU]" 
(238): here

cunumeric/stat/bincount.cu(75): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, const double)
          detected during:
            instantiation of "void cunumeric::_weighted_bincount(double *, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)4>]" 
(130): here
            instantiation of "void cunumeric::weighted_bincount_kernel_rd(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)4>]" 
(209): here
            instantiation of "void cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::operator()(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, const legate::AccessorRO<cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::VAL, 1, Legion::coord_t> &, const legate::AccessorRO<double, 1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &) const [with CODE=(legate::LegateTypeCode)4]" 
./cunumeric/stat/bincount_template.inl(41): here
            instantiation of "void cunumeric::BincountImpl<KIND>::operator()<CODE,<unnamed>>(cunumeric::BincountArgs &) const [with KIND=cunumeric::VariantKind::GPU, CODE=INT64_LT, <unnamed>=(void *)nullptr]" 
./cunumeric/stat/bincount_template.inl(62): here
            instantiation of "void cunumeric::bincount_template<KIND>(legate::TaskContext &) [with KIND=cunumeric::VariantKind::GPU]" 
(238): here

cunumeric/stat/bincount.cu(75): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, const double)
          detected during:
            instantiation of "void cunumeric::_weighted_bincount(double *, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)5>]" 
(130): here
            instantiation of "void cunumeric::weighted_bincount_kernel_rd(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)5>]" 
(209): here
            instantiation of "void cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::operator()(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, const legate::AccessorRO<cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::VAL, 1, Legion::coord_t> &, const legate::AccessorRO<double, 1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &) const [with CODE=(legate::LegateTypeCode)5]" 
./cunumeric/stat/bincount_template.inl(41): here
            instantiation of "void cunumeric::BincountImpl<KIND>::operator()<CODE,<unnamed>>(cunumeric::BincountArgs &) const [with KIND=cunumeric::VariantKind::GPU, CODE=UINT8_LT, <unnamed>=(void *)nullptr]" 
./cunumeric/stat/bincount_template.inl(62): here
            instantiation of "void cunumeric::bincount_template<KIND>(legate::TaskContext &) [with KIND=cunumeric::VariantKind::GPU]" 
(238): here

cunumeric/stat/bincount.cu(75): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, const double)
          detected during:
            instantiation of "void cunumeric::_weighted_bincount(double *, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)6>]" 
(130): here
            instantiation of "void cunumeric::weighted_bincount_kernel_rd(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)6>]" 
(209): here
            instantiation of "void cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::operator()(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, const legate::AccessorRO<cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::VAL, 1, Legion::coord_t> &, const legate::AccessorRO<double, 1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &) const [with CODE=(legate::LegateTypeCode)6]" 
./cunumeric/stat/bincount_template.inl(41): here
            instantiation of "void cunumeric::BincountImpl<KIND>::operator()<CODE,<unnamed>>(cunumeric::BincountArgs &) const [with KIND=cunumeric::VariantKind::GPU, CODE=UINT16_LT, <unnamed>=(void *)nullptr]" 
./cunumeric/stat/bincount_template.inl(62): here
            instantiation of "void cunumeric::bincount_template<KIND>(legate::TaskContext &) [with KIND=cunumeric::VariantKind::GPU]" 
(238): here

cunumeric/stat/bincount.cu(75): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, const double)
          detected during:
            instantiation of "void cunumeric::_weighted_bincount(double *, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)7>]" 
(130): here
            instantiation of "void cunumeric::weighted_bincount_kernel_rd(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)7>]" 
(209): here
            instantiation of "void cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::operator()(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, const legate::AccessorRO<cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::VAL, 1, Legion::coord_t> &, const legate::AccessorRO<double, 1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &) const [with CODE=(legate::LegateTypeCode)7]" 
./cunumeric/stat/bincount_template.inl(41): here
            instantiation of "void cunumeric::BincountImpl<KIND>::operator()<CODE,<unnamed>>(cunumeric::BincountArgs &) const [with KIND=cunumeric::VariantKind::GPU, CODE=UINT32_LT, <unnamed>=(void *)nullptr]" 
./cunumeric/stat/bincount_template.inl(62): here
            instantiation of "void cunumeric::bincount_template<KIND>(legate::TaskContext &) [with KIND=cunumeric::VariantKind::GPU]" 
(238): here

cunumeric/stat/bincount.cu(75): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, const double)
          detected during:
            instantiation of "void cunumeric::_weighted_bincount(double *, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)8>]" 
(130): here
            instantiation of "void cunumeric::weighted_bincount_kernel_rd(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, legate::AccessorRO<VAL, 1, Legion::coord_t>, legate::AccessorRO<double, 1, Legion::coord_t>, size_t, size_t, Legion::Point<1, Legion::coord_t>) [with VAL=legate::legate_type_of<(legate::LegateTypeCode)8>]" 
(209): here
            instantiation of "void cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::operator()(legate::AccessorRD<Legion::SumReduction<double>, false, 1, Legion::coord_t>, const legate::AccessorRO<cunumeric::BincountImplBody<cunumeric::VariantKind::GPU, CODE>::VAL, 1, Legion::coord_t> &, const legate::AccessorRO<double, 1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &, const Legion::Rect<1, Legion::coord_t> &) const [with CODE=(legate::LegateTypeCode)8]" 
./cunumeric/stat/bincount_template.inl(41): here
            instantiation of "void cunumeric::BincountImpl<KIND>::operator()<CODE,<unnamed>>(cunumeric::BincountArgs &) const [with KIND=cunumeric::VariantKind::GPU, CODE=UINT64_LT, <unnamed>=(void *)nullptr]" 
./cunumeric/stat/bincount_template.inl(62): here
            instantiation of "void cunumeric::bincount_template<KIND>(legate::TaskContext &) [with KIND=cunumeric::VariantKind::GPU]" 
(238): here

9 errors detected in the compilation of "/tmp/tmpxft_00001ff9_00000000-6_bincount.cpp1.ii".
/usr/local/legate/share/legate/legate.mk:205: recipe for target 'cunumeric/stat/bincount.cu.o' failed
make: * [cunumeric/stat/bincount.cu.o] Error 1
make: * Waiting for unfinished jobs....
Traceback (most recent call last):
  File "install.py", line 495, in <module>
    driver()
  File "install.py", line 491, in driver
    install_cunumeric(unknown=unknown, **vars(args))
  File "install.py", line 387, in install_cunumeric
    unknown,
  File "install.py", line 255, in build_cunumeric
    verbose=verbose,
  File "install.py", line 84, in execute_command
    subprocess.check_call(args, cwd=cwd, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'LEGATE_DIR=/usr/local/legate', 'OPEN_BLAS_DIR=/usr/local/legate/OpenBLAS', 'DEBUG=0', 'DEBUG_RELEASE=0', 'CHECK_BOUNDS=0', 'PREFIX=/usr/local/legate', 'OPENBLAS_FLAGS = -L/usr/local/legate/OpenBLAS/lib -lopenblas_legate -Wl,-rpath,/usr/local/legate/OpenBLAS/lib', '-j', '4', 'install']' returned non-zero exit status 2.

**Comment by magnatelee** [comment]
I see the cause here; the atomic addition for doubles is not available for compute capabilities < 6. Though it wasn't stated anywhere, we actually didn't plan to support architectures older than Pascal. That said, I think there are a couple of easy fixes for this. Let me figure out a right one.

**Comment by milwd** [comment]
Thank you sir, I'll be looking forward to hearing from you :)

**Comment by magnatelee** [comment]
The issue should be fixed by #136. @milwd Can you pull and try again?

**Comment by milwd** [comment]
I did, the compilation passed the "bincount" stage :)
but then this happened ->

... compile messages ...
```
/usr/local/cuda-10/bin/nvcc -o cunumeric/unary/unary_op.cu.d -M cunumeric/unary/unary_op.cu  -I/usr/local/legate/thrust  -I. -Wno-deprecated-declarations -std=c++14 --expt-relaxed-constexpr --expt-extended-lambda -ccbin=g++ -I/usr/local/legate/include -O2 -DMAXWELL_ARCH -gencode arch=compute_52,code=sm_52 -DLEGATE_USE_CUDA -I/usr/local/cuda-10/include --compiler-options '-fPIC'
/usr/local/cuda-10/bin/nvcc -o cunumeric/unary/unary_op.cu.o -c cunumeric/unary/unary_op.cu  -I/usr/local/legate/thrust  -I. -Wno-deprecated-declarations -std=c++14 --expt-relaxed-constexpr --expt-extended-lambda -ccbin=g++ -I/usr/local/legate/include -O2 -DMAXWELL_ARCH -gencode arch=compute_52,code=sm_52 -DLEGATE_USE_CUDA -I/usr/local/cuda-10/include --compiler-options '-fPIC'
./cunumeric/unary/unary_op_util.h(309): error: identifier "hexp2" is undefined

./cunumeric/unary/unary_op_util.h(446): error: identifier "hlog10" is undefined

./cunumeric/unary/unary_op_util.h(553): error: identifier "__heq" is undefined

./cunumeric/unary/unary_op_util.h(555): error: identifier "__hgt" is undefined

./cunumeric/unary/unary_op_util.h(539): warning: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "cunumeric::UnaryOp<cunumeric::UnaryOpCode::SIGN, CODE>::T cunumeric::UnaryOp<cunumeric::UnaryOpCode::SIGN, CODE>::_sign(const _T &) const [with CODE=BOOL_LT, _T=legate::legate_type_of<(legate::LegateTypeCode)0>]" 
./cunumeric/unary/unary_op_template.inl(90): here
            instantiation of "void cunumeric::unary_op_template<KIND>(legate::TaskContext &) [with KIND=cunumeric::VariantKind::GPU]" 
cunumeric/unary/unary_op.cu(72): here

./cunumeric/unary/unary_op_util.h(539): warning: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "cunumeric::UnaryOp<cunumeric::UnaryOpCode::SIGN, CODE>::T cunumeric::UnaryOp<cunumeric::UnaryOpCode::SIGN, CODE>::_sign(const _T &) const [with CODE=UINT8_LT, _T=legate::legate_type_of<(legate::LegateTypeCode)5>]" 
./cunumeric/unary/unary_op_template.inl(90): here
            instantiation of "void cunumeric::unary_op_template<KIND>(legate::TaskContext &) [with KIND=cunumeric::VariantKind::GPU]" 
cunumeric/unary/unary_op.cu(72): here

./cunumeric/unary/unary_op_util.h(539): warning: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "cunumeric::UnaryOp<cunumeric::UnaryOpCode::SIGN, CODE>::T cunumeric::UnaryOp<cunumeric::UnaryOpCode::SIGN, CODE>::_sign(const _T &) const [with CODE=UINT16_LT, _T=legate::legate_type_of<(legate::LegateTypeCode)6>]" 
./cunumeric/unary/unary_op_template.inl(90): here
            instantiation of "void cunumeric::unary_op_template<KIND>(legate::TaskContext &) [with KIND=cunumeric::VariantKind::GPU]" 
cunumeric/unary/unary_op.cu(72): here

./cunumeric/unary/unary_op_util.h(539): warning: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "cunumeric::UnaryOp<cunumeric::UnaryOpCode::SIGN, CODE>::T cunumeric::UnaryOp<cunumeric::UnaryOpCode::SIGN, CODE>::_sign(const _T &) const [with CODE=UINT32_LT, _T=legate::legate_type_of<(legate::LegateTypeCode)7>]" 
./cunumeric/unary/unary_op_template.inl(90): here
            instantiation of "void cunumeric::unary_op_template<KIND>(legate::TaskContext &) [with KIND=cunumeric::VariantKind::GPU]" 
cunumeric/unary/unary_op.cu(72): here

./cunumeric/unary/unary_op_util.h(539): warning: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "cunumeric::UnaryOp<cunumeric::UnaryOpCode::SIGN, CODE>::T cunumeric::UnaryOp<cunumeric::UnaryOpCode::SIGN, CODE>::_sign(const _T &) const [with CODE=UINT64_LT, _T=Legion::LayoutConstraintID]" 
./cunumeric/unary/unary_op_template.inl(90): here
            instantiation of "void cunumeric::unary_op_template<KIND>(legate::TaskContext &) [with KIND=cunumeric::VariantKind::GPU]" 
cunumeric/unary/unary_op.cu(72): here

4 errors detected in the compilation of "/tmp/tmpxft_00001644_00000000-6_unary_op.cpp1.ii".
/usr/local/legate/share/legate/legate.mk:205: recipe for target 'cunumeric/unary/unary_op.cu.o' failed
make: * [cunumeric/unary/unary_op.cu.o] Error 1
make: * Waiting for unfinished jobs....
Traceback (most recent call last):
  File "install.py", line 495, in <module>
    driver()
  File "install.py", line 491, in driver
    install_cunumeric(unknown=unknown, **vars(args))
  File "install.py", line 387, in install_cunumeric
    unknown,
  File "install.py", line 255, in build_cunumeric
    verbose=verbose,
  File "install.py", line 84, in execute_command
    subprocess.check_call(args, cwd=cwd, shell=shell)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', 'LEGATE_DIR=/usr/local/legate', 'OPEN_BLAS_DIR=/usr/local/legate/OpenBLAS', 'DEBUG=0', 'DEBUG_RELEASE=0', 'CHECK_BOUNDS=0', 'PREFIX=/usr/local/legate', 'OPENBLAS_FLAGS = -L/usr/local/legate/OpenBLAS/lib -lopenblas_legate -Wl,-rpath,/usr/local/legate/OpenBLAS/lib', '-j', '4', 'install']' returned non-zero exit status 2.
```

**Comment by manopapad** [comment]
It looks like we are not finding certain half-precision functions, even though these functions should be available under all CUDA Runtime 10.x versions. Could you please share the output of the following commands?

```
cat <legate_install_dir>/include/legion_defines.h
```

and

```
grep -r hlog10 /usr/local/cuda-10/include
```

**Comment by lightsighter** [comment]
I wouldn't be surprised if the half precision hardware is not available on Jetson GPUs (e.g. Maxwell architecture), and therefore it won't be available in CUDA even when using a recent version of CUDA (e.g. >= 10.x). We might want to provide a way to build cuNumeric without native half-precision support, or just emulate it like we do on CPUs using our own `__half` type that converts to `float` for each operation and back at the end.

**Comment by milwd** [comment]
Sure
the output of  `$ cat /usr/local/legate/include/legion_defines.h`  =>
```
/**
* \file legion_defines.h
* Public-facing definitions of variables configured at build time
* DO NOT EDIT THIS FILE WITHOUT CHANGING runtime.mk ALSO
*/
/********************** IMPORTANT **************************
*
* This file is PURE C, **NOT** C++. Keep any C++-isms in
* legion_types.h, or elsewhere.
*
******************** IMPORTANT ****************************/
#define LEGION_VERSION "legion-21.09.0-3008-g035411247"
/* #undef DEBUG_LEGION */
/* #undef LEGION_PRIVILEGE_CHECKS */
/* #undef LEGION_BOUNDS_CHECKS */
#define LEGION_MAX_DIM 4
#define LEGION_MAX_FIELDS 256
#define LEGION_USE_CUDA
/* #undef LEGION_GPU_REDUCTIONS */
#define LEGION_USE_ZLIB
#define LEGION_REDOP_COMPLEX
#define LEGION_REDOP_HALF
/* #undef LEGION_WARNINGS_FATAL */
/* #undef LEGION_USE_HDF5 */
/* #undef LEGION_SPY */
/* #undef LEGION_USE_HIP */
#define LEGION_USE_LIBDL
```

and the output of  `$ grep -r hlog10 /usr/local/cuda-10/include`  =>
```
/usr/local/cuda-10/include/cuda_fp16.h:__CUDA_FP16_DECL__ __half hlog10(const __half a);
/usr/local/cuda-10/include/cuda_fp16.hpp:__CUDA_FP16_DECL__ __half hlog10(const __half a) {

```
