### ISSUE TITLE
Dot: support for all modes

### ISSUE THREAD

**Issue by astroboylrx** [nv-legate/cunumeric#132]
I created a new env for `legate` and installed `cunumeric` with
```bash
conda install -c nvidia -c conda-forge -c legate legate-core
conda install -c nvidia -c conda-forge -c legate cunumeric
```

Simple functions work and the speed-up is great (e.g., `np.cos(np.random.randn(int(1e8))`). By the way, the docker image mentioned in the [quickstart](https://github.com/nv-legate/quickstart) does not contain the `# CuNumeric 2d stencil example` because there is no folder named `cunumeric` under `/opt/legate/`.

Anyway, I ran into a weird issue while testing `np.dot(1D-array, 3D-array)`, where `assert lhs_array.ndim == 1` fails if the array size is larger than 10. See below for demonstration.

```bash
(legate) ➜  cunumeric_test legate                                                                                                                                       [15:40:34]
WARNING: Disabling control replication for interactive run
[0 - 7f40317da000]    0.000000 {4}{threads}: can't open /sys/devices/system/node
[0 - 7f40317da000]    0.000054 {4}{threads}: reservation ('CPU proc 1d00000000000003') cannot be satisfied
Welcome to Legion Python interactive console
>>> import cunumeric as np
>>> size = 3; A = np.random.random(size); F = np.random.random((size, size, size))
>>> A.dot(F)
array([[1.45762329, 1.13836616, 0.87031347],
       [0.91886628, 0.58458267, 1.02779656],
       [1.22524198, 0.6921081 , 1.18912413]])
>>> size = 10; A = np.random.random(size); F = np.random.random((size, size, size))
>>> A.dot(F)
array([[1.12846535, 2.14166178, 1.18252206, 2.01743539, 1.65099152,
        2.04467931, 2.46226495, 3.15380793, 1.86828431, 1.93982547],
       [2.3986243 , 2.01096514, 2.78841009, 1.50467153, 3.16122549,
        2.14065189, 2.95369028, 2.68103247, 2.3120522 , 2.00948703],
       [2.35879704, 1.19883355, 2.56835745, 1.87652231, 2.02573379,
        2.6082775 , 3.41437887, 1.99271167, 3.06575268, 2.36509391],
       [2.53859196, 3.1121264 , 1.94441658, 1.89393396, 1.96443314,
        1.87471477, 1.93022662, 3.32724628, 2.35590026, 2.6420949 ],
       [1.63747279, 1.98088463, 2.82110686, 2.51207595, 2.7798079 ,
        1.97536936, 2.09914834, 2.47306303, 1.91055746, 2.47223346],
       [1.62762168, 1.18327989, 3.02978735, 1.69811497, 2.10315436,
        2.11446031, 2.21917527, 1.0845954 , 2.44741341, 1.6781611 ],
       [2.30392027, 1.79668444, 2.1445187 , 2.39125851, 1.05225545,
        1.61600473, 2.09620947, 2.52730665, 2.22931053, 1.85043438],
       [2.86261427, 2.53997426, 2.22975254, 1.73346629, 2.29874538,
        2.61097697, 1.49579078, 2.57901499, 2.00547838, 1.70844441],
       [2.47710508, 2.84444594, 1.27922792, 2.50987714, 2.65934434,
        1.52033334, 1.98116439, 2.18125422, 2.34385632, 2.5185199 ],
       [1.79341747, 2.55603121, 2.2968819 , 2.3483017 , 1.56720313,
        1.89994937, 2.28222509, 2.18620959, 1.63716249, 1.79328127]])
>>> size = 11; A = np.random.random(size); F = np.random.random((size, size, size))
>>> A.dot(F)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/rixin/opt/miniconda3/envs/legate/lib/python3.9/site-packages/cunumeric/array.py", line 1091, in dot
    out._thunk.dot(
  File "/home/rixin/opt/miniconda3/envs/legate/lib/python3.9/site-packages/cunumeric/deferred.py", line 82, in wrapper
    result = func(*args, **kwargs)
  File "/home/rixin/opt/miniconda3/envs/legate/lib/python3.9/site-packages/cunumeric/deferred.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/rixin/opt/miniconda3/envs/legate/lib/python3.9/site-packages/cunumeric/deferred.py", line 98, in wrapper
    return func(*args, **kwargs)
  File "/home/rixin/opt/miniconda3/envs/legate/lib/python3.9/site-packages/cunumeric/deferred.py", line 930, in dot
    assert lhs_array.ndim == 1
AssertionError
>>>
```

Not really sure what happened, but from the code it seems the `lhs` does not refer to the input 1D-array. Instead, it is a deferred array for output(?). Is this a bug? Any suggestions are appreciated! Let me know if more info is needed.

**Comment by manopapad** [comment]
> By the way, the docker image mentioned in the quickstart does not contain the # CuNumeric 2d stencil example because there is no folder named cunumeric under /opt/legate/.

Yeah, those images are a little old at this point. We might be discontinuing them since we now have conda packages, I'll need to discuss with the rest of the team.

> Not really sure what happened, but from the code it seems the lhs does not refer to the input 1D-array. Instead, it is a deferred array for output(?). Is this a bug? Any suggestions are appreciated! Let me know if more info is needed.

The underlying issue is that the accelerated codepath in cuNumeric (aka "deferred" execution mode) does not yet support `dot` between 1d and 3d arrays. You don't see this error on the smaller sizes because for those cuNumeric decided it's not worth accelerating, and fell back to standard NumPy.

I updated the error message to be more informative (https://github.com/nv-legate/cunumeric/pull/133, waiting for CI), and will keep this issue open to track work on implementing these cases.

**Comment by astroboylrx** [comment]
I see. Thanks a lot for the explanations! And looking forward to future implementations.

**Comment by manopapad** [comment]
With the merge of https://github.com/nv-legate/cunumeric/pull/217 all dot modes are now supported.
