### ISSUE TITLE
make `copy` work for unaligned color spaces in partitions

### ISSUE THREAD

**Issue by ipdemes** [nv-legate/cunumeric#203]
`copy` doesn't seem to support following case:
code:
```
     copy = self.context.create_copy()
     copy.add_input(self.base)
     copy.add_source_indirect(index_array.base)
     copy.add_output(result.base)
     copy.add_alignment(index_array.base, result.base)
     copy.execute()
```
where
`self` has shape [2,3,4]
`index_array` has shape [2,2] and field type Point<3> (points to `self`)
`result` has shape [2,2] and type of `self`

returns error:

```
[0 - 70000e772000]    2.805318 {6}{python}: python exception occurred within task:
Traceback (most recent call last):
  File "/Users/idemeshko/src/legate_core/lib/python3.8/site-packages/legion_top.py", line 410, in legion_python_main
    run_path(args[start], run_name='__main__')
  File "/Users/idemeshko/src/legate_core/lib/python3.8/site-packages/legion_top.py", line 234, in run_path
IRINA DEBUG idex_rect = <0,1>..<1,1>out_rect = <0,1>..<1,1>
    exec(code, module.__dict__, module.__dict__)
  File "tests/index_routines.py", line 231, in <module>
IRINA DEBUG idex_rect = <0,0>..<1,0>out_rect = <0,0>..<1,0>
    test()
  File "tests/index_routines.py", line 225, in test
    advanced_indexing()
  File "tests/index_routines.py", line 49, in advanced_indexing
    res = z_num[indx2_num, indx1_num, indx0_num]
  File "/Users/idemeshko/development/cunumeric_compress/cunumeric/array.py", line 138, in wrapper
    return func(*args, **kwargs)
  File "/Users/idemeshko/development/cunumeric_compress/cunumeric/array.py", line 445, in __getitem__
    return ndarray(shape=None, thunk=self._thunk.get_item(key))
  File "/Users/idemeshko/development/cunumeric_compress/cunumeric/deferred.py", line 472, in get_item
    copy.execute()
  File "/Users/idemeshko/src/legate_core/lib/python3.8/site-packages/legate/core/operation.py", line 152, in execute
    self._context.runtime.submit(self)
  File "/Users/idemeshko/src/legate_core/lib/python3.8/site-packages/legate/core/runtime.py", line 927, in submit
    self.flush_scheduling_window()
  File "/Users/idemeshko/src/legate_core/lib/python3.8/site-packages/legate/core/runtime.py", line 922, in flush_scheduling_window
    self._schedule(ops)
  File "/Users/idemeshko/src/legate_core/lib/python3.8/site-packages/legate/core/runtime.py", line 912, in _schedule
    strategies.append(partitioner.partition_stores())
  File "/Users/idemeshko/src/legate_core/lib/python3.8/site-packages/legate/core/solver.py", line 331, in partition_stores
    raise NotImplementedError(
NotImplementedError: Found unaligned color spaces in partitions. Auto-partitioner needs to be extended for this case.
Assertion failed: (0), function execute_task, file /Users/idemeshko/development/legate.core/legion/runtime/realm/python/python_module.cc, line 992.
```

The error can be reproduced in [this ](https://github.com/ipdemes/cunumeric/tree/advanced_indexing)branch by running:
`legate tests/index_routines.py -cunumeric:test --cpus 2`

**Comment by magnatelee** [comment]
@ipdemes I believe this is already fixed by nv-legate/legate.core#157. Can we close this?

**Comment by ipdemes** [comment]
Yes, it is fixed. closing.
