### ISSUE TITLE
Weights are all 0s when creating a Weight object from FutureMap 

### ISSUE THREAD

**Issue by manopapad** [nv-legate/cunumeric#375]
Running this program:

```
import cunumeric as cn

if __name__ == "__main__":
    a = cn.array([1, 2, 3, 4, 5])
    rep = cn.array([1, 2, 1, 2, 1])
    x = cn.repeat(a, rep, axis=0)
    x + x
```

on 2 CPUs, as follows:

```
legate a.py -cunumeric:test --cpus 2
```

crashes with an arithmetic exception, with the following backtrace:

<details>
 <summary>backtrace (click to expand)</summary>

```
Thread 14 "legion_python" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7f9cb0be1700 (LWP 58549)]
0x00007ffff3765e61 in Realm::IndexSpace<1, long long>::create_weighted_subspaces (this=0x7f9cb0bdc9c0, count=2, granularity=1, weights=..., subspaces=..., reqs=..., wait_on=...) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/deppart/partitions.cc:365
365	        if((total_x % total_weight) == 0)
(gdb) bt
#0  0x00007ffff3765e61 in Realm::IndexSpace<1, long long>::create_weighted_subspaces (this=0x7f9cb0bdc9c0, count=2, granularity=1, weights=..., subspaces=..., reqs=..., wait_on=...) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/deppart/partitions.cc:365
#1  0x00007ffff6fe5dfe in Legion::Internal::IndexSpaceNodeT<1, long long>::create_by_weight_helper<1, long long> (this=0x7f9e1d038490, op=0x7f9e1cfe80c0, partition=0x7f9e1d029f30, future_map=0x7f9e1d004e60, granularity=1, shard=0, total_shards=1) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/legion/region_tree.inl:4747
#2  0x00007ffff6e38807 in Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper::demux<Realm::DynamicTemplates::Int<1>, long long> (creator=0x7f9cb0bdcd40) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/legion/region_tree.h:2805
#3  0x00007ffff6e37b34 in Realm::DynamicTemplates::ListProduct2<Realm::DynamicTemplates::IntList<1, 4>, Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> > > >::DemuxHelper2<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper, Realm::DynamicTemplates::Int<1> >::demux<long long, Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper*> (arg1=0x7f9cb0bdcd40) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/dynamic_templates.inl:190
#4  0x00007ffff6e35e9f in Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm>::DemuxHelper<Realm::DynamicTemplates::ListProduct2<Realm::DynamicTemplates::IntList<1, 4>, Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> > > >::DemuxHelper2<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper, Realm::DynamicTemplates::Int<1> >, 2>::demux<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper*> (index=2, arg1=0x7f9cb0bdcd40) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/dynamic_templates.inl:37
#5  0x00007ffff6e33354 in Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> >::DemuxHelper<Realm::DynamicTemplates::ListProduct2<Realm::DynamicTemplates::IntList<1, 4>, Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> > > >::DemuxHelper2<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper, Realm::DynamicTemplates::Int<1> >, 1>::demux<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper*> (index=2, arg1=0x7f9cb0bdcd40) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/dynamic_templates.inl:39
#6  0x00007ffff6e3025a in Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> > >::DemuxHelper<Realm::DynamicTemplates::ListProduct2<Realm::DynamicTemplates::IntList<1, 4>, Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> > > >::DemuxHelper2<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper, Realm::DynamicTemplates::Int<1> >, 0>::demux<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper*> (index=2, arg1=0x7f9cb0bdcd40) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/dynamic_templates.inl:39
#7  0x00007ffff6e2d29e in Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> > >::demux<Realm::DynamicTemplates::ListProduct2<Realm::DynamicTemplates::IntList<1, 4>, Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> > > >::DemuxHelper2<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper, Realm::DynamicTemplates::Int<1> >, Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper*> (index=2, arg1=0x7f9cb0bdcd40) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/dynamic_templates.inl:79
#8  0x00007ffff6e2aa79 in Realm::DynamicTemplates::ListProduct2<Realm::DynamicTemplates::IntList<1, 4>, Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> > > >::DemuxHelper1<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper>::demux<Realm::DynamicTemplates::Int<1>, Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper*> (tag=258, arg1=0x7f9cb0bdcd40) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/dynamic_templates.inl:215
#9  0x00007ffff6e27ee7 in Realm::DynamicTemplates::IntDemuxHelper<Realm::DynamicTemplates::ListProduct2<Realm::DynamicTemplates::IntList<1, 4>, Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> > > >::DemuxHelper1<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper>, 1, 0>::demux<unsigned int, Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper*> (index=1, arg1=258, arg2=0x7f9cb0bdcd40) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/dynamic_templates.h:222
#10 0x00007ffff6e24cf2 in Realm::DynamicTemplates::IntDemuxHelper<Realm::DynamicTemplates::ListProduct2<Realm::DynamicTemplates::IntList<1, 4>, Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> > > >::DemuxHelper1<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper>, 1, 1>::demux<unsigned int, Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper*> (index=1, arg1=258, arg2=0x7f9cb0bdcd40) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/dynamic_templates.h:189
#11 0x00007ffff6e20c26 in Realm::DynamicTemplates::IntDemuxHelper<Realm::DynamicTemplates::ListProduct2<Realm::DynamicTemplates::IntList<1, 4>, Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> > > >::DemuxHelper1<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper>, 1, 2>::demux<unsigned int, Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper*> (index=1, arg1=258, arg2=0x7f9cb0bdcd40) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/dynamic_templates.h:189
#12 0x00007ffff6e1b88f in Realm::DynamicTemplates::IntDemuxHelper<Realm::DynamicTemplates::ListProduct2<Realm::DynamicTemplates::IntList<1, 4>, Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> > > >::DemuxHelper1<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper>, 1, 3>::demux<unsigned int, Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper*> (index=1, arg1=258, arg2=0x7f9cb0bdcd40) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/dynamic_templates.h:189
#13 0x00007ffff6e12db0 in Realm::DynamicTemplates::IntList<1, 4>::demux<Realm::DynamicTemplates::ListProduct2<Realm::DynamicTemplates::IntList<1, 4>, Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> > > >::DemuxHelper1<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper>, unsigned int, Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper*> (index=1, arg1=258, arg2=0x7f9cb0bdcd40) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/dynamic_templates.inl:154
#14 0x00007ffff6dffac4 in Realm::DynamicTemplates::ListProduct2<Realm::DynamicTemplates::IntList<1, 4>, Realm::DynamicTemplates::TypeListElem<int, Realm::DynamicTemplates::TypeListElem<unsigned int, Realm::DynamicTemplates::TypeListElem<long long, Realm::DynamicTemplates::TypeListTerm> > > >::demux<Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper, Legion::Internal::IndexSpaceNodeT<1, long long>::CreateByWeightHelper*> (tag=258, arg1=0x7f9cb0bdcd40) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/dynamic_templates.inl:241
#15 0x00007ffff6de5477 in Legion::Internal::IndexSpaceNodeT<1, long long>::create_by_weights (this=0x7f9e1d038490, op=0x7f9e1cfe80c0, partition=0x7f9e1d029f30, future_map=0x7f9e1d004e60, granularity=1, shard=0, total_shards=1) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/legion/region_tree.inl:4488
#16 0x00007ffff6b1e793 in Legion::Internal::IndexPartNode::create_by_weights (this=0x7f9e1d029f30, op=0x7f9e1cfe80c0, weights=..., granularity=1, shard=0, total_shards=1) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/legion/region_tree.cc:11236
#17 0x00007ffff6af1bc4 in Legion::Internal::RegionTreeForest::create_partition_by_weights (this=0x542dc0, op=0x7f9e1cfe80c0, pid=..., weights=..., granularity=1, shard=0, total_shards=1) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/legion/region_tree.cc:839
#18 0x00007ffff668855f in Legion::Internal::PendingPartitionOp::WeightPartitionThunk::perform (this=0x7f9e1d038f90, op=0x7f9e1cfe80c0, forest=0x542dc0) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/legion/legion_ops.h:2850
#19 0x00007ffff6663ecc in Legion::Internal::PendingPartitionOp::trigger_complete (this=0x7f9e1cfe80c0) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/legion/legion_ops.cc:15730
#20 0x00007ffff66284e8 in Legion::Internal::Operation::complete_execution (this=0x7f9e1cfe80c0, wait_on=...) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/legion/legion_ops.cc:1374
#21 0x00007ffff6663e3e in Legion::Internal::PendingPartitionOp::trigger_mapping (this=0x7f9e1cfe80c0) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/legion/legion_ops.cc:15722
#22 0x00007ffff6c1d21d in Legion::Internal::Runtime::legion_runtime_task (args=0x7f9e0c008070, arglen=12, userdata=0x585a10, userlen=8, p=...) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/legion/runtime.cc:31253
#23 0x00007ffff39a50da in Realm::LocalTaskProcessor::execute_task (this=0x53c430, func_id=4, task_args=...) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/proc_impl.cc:1135
#24 0x00007ffff3736d88 in Realm::Task::execute_on_processor (this=0x7f9e0c007ef0, p=...) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/tasks.cc:302
#25 0x00007ffff373a922 in Realm::KernelThreadTaskScheduler::execute_task (this=0x53c640, task=0x7f9e0c007ef0) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/tasks.cc:1355
#26 0x00007ffff37397f3 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x53c640) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/tasks.cc:1094
#27 0x00007ffff3739dc6 in Realm::ThreadedTaskScheduler::scheduler_loop_wlock (this=0x53c640) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/tasks.cc:1206
#28 0x00007ffff374101a in Realm::Thread::thread_entry_wrapper<Realm::ThreadedTaskScheduler, &Realm::ThreadedTaskScheduler::scheduler_loop_wlock> (obj=0x53c640) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/threads.inl:97
#29 0x00007ffff3713311 in Realm::KernelThread::pthread_entry (data=0x7f9e0c0237f0) at /gpfs/fs1/mpapadakis/legate.core/legion/runtime/realm/threads.cc:774
#30 0x00007ffff29fb6db in start_thread (arg=0x7f9cb0be1700) at pthread_create.c:463
#31 0x00007ffff07e471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
</details>

After some debugging, and with help from @lightsighter, I discovered that the underlying issue is that all weights are 0 when the core creates the `Weighted` partition object:

```
Making Weighted object with weights = <legate.core._legion.future.FutureMap object at 0x7f4a4dbf8940>
waiting for weights
weights[0] = b'\x00\x00\x00\x00\x00\x00\x00\x00'
weights[1] = b'\x00\x00\x00\x00\x00\x00\x00\x00'
```

**Comment by magnatelee** [comment]
Should be fixed by https://github.com/nv-legate/legate.core/pull/243

**Comment by magnatelee** [comment]
https://github.com/nv-legate/legate.core/pull/243 is merged. feel free to close the issue once you confirm the fix
