### ISSUE TITLE
Clip crashes for int-type arrays with max=None

### ISSUE THREAD

**Issue by manopapad** [nv-legate/cunumeric#483]
```
x = cn.arange(6)
print(x.clip(2, None))
```

crashes with:

```
Traceback (most recent call last):
  File "/Users/mpapadakis/legate.core/install/lib/python3.8/site-packages/legion_top.py", line 440, in legion_python_main
    run_path(args[start], run_name='__main__')
  File "/Users/mpapadakis/legate.core/install/lib/python3.8/site-packages/legion_top.py", line 255, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "a.py", line 17, in <module>
    print(x.clip(2, None))
  File "/Users/mpapadakis/cunumeric/cunumeric/coverage.py", line 107, in wrapper
    return func(*args, **kwargs)
  File "/Users/mpapadakis/cunumeric/cunumeric/array.py", line 2109, in clip
    np.array(max, dtype=self.dtype),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

This works for `float`-type arrays, because `np.array(None, dtype=np.float64)` ends up calling `np.float64(None)`, which returns `NaN`, and that produces the required result (the corresponding limit is ignored). Conversely, `np.array(None, dtype=int)` invokes `int(None)`, which is not allowed.

**Comment by magnatelee** [comment]
Let's take this as an excuse to build a complete implementation for `clip` supporting array arguments for `a_min` and `a_max`. A proper fix would make it a ternary operator, as there are potentially up to three array arguments.
