### ISSUE TITLE
reshape doesn't match numpy semantics

### ISSUE THREAD

**Issue by rohany** [nv-legate/cunumeric#489]
```
>>> import numpy
>>> import cunumeric
>>> x = cunumeric.ones((25))
>>> x.reshape(-1, 5)
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])
>>> numpy.reshape(x, (-1, 5))
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])
>>>
```

**Comment by manopapad** [comment]
I think this is working fine right now, you just forgot to put the new shape in a tuple
```
x.reshape((-1, 5))
```

**Comment by manopapad** [comment]
Actually, it looks like the underlying issue here is that the `np.ndarray.reshape` method allows the dimensions to be passed as separate numbers:

```
>>> np.ones((3,4)).reshape(-1, 2, 3).shape
(2, 2, 3)
```

in contrast to the module-level function:

```
>>> np.reshape(np.ones((3,4)), -1, 2, 3).shape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 179, in reshape
TypeError: _reshape_dispatcher() takes from 2 to 3 positional arguments but 4 were given
>>> np.reshape(np.ones((3,4)), -1, 2).shape
Traceback (most recent call last):
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
TypeError: order must be str, not int
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<__array_function__ internals>", line 180, in reshape
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 66, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 43, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
TypeError: order must be str, not int
```

This is a documented behavior: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html#numpy.ndarray.reshape

**Comment by rohany** [comment]
> I think this is working fine right now, you just forgot to put the new shape in a tuple

Thanks, this works

**Comment by magnatelee** [comment]
this is a known issue: https://github.com/nv-legate/cunumeric/issues/127
