### ISSUE TITLE
crash using result from `np.sum`

### ISSUE THREAD

**Issue by rohany** [nv-legate/cunumeric#493]
```
>>> import cunumeric
>>> x = cunumeric.ones((5,))
>>> y = x.sum()
>>> cunumeric.zeros(y, dtype=int)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/coverage.py", line 107, in wrapper
    return func(*args, **kwargs)
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/module.py", line 296, in zeros
    return full(shape, 0, dtype=dtype)
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/module.py", line 368, in full
    result = empty(shape, dtype=val.dtype)
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/module.py", line 89, in empty
    return ndarray(shape=shape, dtype=dtype)
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/coverage.py", line 107, in wrapper
    return func(*args, **kwargs)
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/array.py", line 197, in __init__
    self._thunk = runtime.create_empty_thunk(shape, dtype, inputs)
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/runtime.py", line 576, in create_empty_thunk
    self.is_eager_shape(computed_shape)
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/runtime.py", line 593, in is_eager_shape
    volume = calculate_volume(shape)
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/utils.py", line 97, in calculate_volume
    if len(shape) == 0:
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/coverage.py", line 107, in wrapper
    return func(*args, **kwargs)
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/array.py", line 1125, in __len__
    return self.shape[0]
IndexError: tuple index out of range
```

**Comment by magnatelee** [comment]
fyi, your reproducer is incorrect in NumPy, as you can't pass a floating point value as a size. here's a correct reproducer:
```
import cunumeric
x = cunumeric.ones((5,), dtype=int)
y = x.sum()
cunumeric.zeros(y, dtype=int)                                                                                                                                                                                                                                                                                                                                                                
```
