### ISSUE TITLE
Crash when running test suite on Mac

### ISSUE THREAD

**Issue by manopapad** [nv-legate/cunumeric#521]
Possibly because of differences in how Python multiprocessing works under Mac.

```
~/cunumeric> ./test.py --cpus 1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/mpapadakis/cunumeric/test.py", line 23, in <module>
    from tests._utils.test_plan import TestPlan
  File "/Users/mpapadakis/cunumeric/tests/_utils/test_plan.py", line 26, in <module>
    from .test_stages import STAGES
  File "/Users/mpapadakis/cunumeric/tests/_utils/test_stages/__init__.py", line 24, in <module>
    from .cpu import CPU
  File "/Users/mpapadakis/cunumeric/tests/_utils/test_stages/cpu.py", line 21, in <module>
    from .test_stage import Shard, StageSpec, TestStage, adjust_workers
  File "/Users/mpapadakis/cunumeric/tests/_utils/test_stages/test_stage.py", line 67, in <module>
    class TestStage(Protocol):
  File "/Users/mpapadakis/cunumeric/tests/_utils/test_stages/test_stage.py", line 98, in TestStage
    _manager: multiprocessing.managers.SyncManager = multiprocessing.Manager()
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:
            if __name__ == '__main__':
                freeze_support()
                ...
        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "./test.py", line 23, in <module>
    from tests._utils.test_plan import TestPlan
  File "/Users/mpapadakis/cunumeric/tests/_utils/test_plan.py", line 26, in <module>
    from .test_stages import STAGES
  File "/Users/mpapadakis/cunumeric/tests/_utils/test_stages/__init__.py", line 24, in <module>
    from .cpu import CPU
  File "/Users/mpapadakis/cunumeric/tests/_utils/test_stages/cpu.py", line 21, in <module>
    from .test_stage import Shard, StageSpec, TestStage, adjust_workers
  File "/Users/mpapadakis/cunumeric/tests/_utils/test_stages/test_stage.py", line 67, in <module>
    class TestStage(Protocol):
  File "/Users/mpapadakis/cunumeric/tests/_utils/test_stages/test_stage.py", line 98, in TestStage
    _manager: multiprocessing.managers.SyncManager = multiprocessing.Manager()
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Users/mpapadakis/opt/miniconda3/envs/legate/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```

**Comment by bryevdv** [comment]
I may have figured out how to work around the OSX `multiprocessing` issues, but then there is a new problem: The lates work on the test runner was all about explicitly setting `--cpu-bind` so that test jobs were pinned to pinned to specific shards. But this implies the presence of `numactl` which does not exist on OSX. 

We will have to have some kind of special-case for OSX but the first question is what should the behavior be?  Should be go back to unsetting `REALM_SYNTHETIC_CORE_MAP` on OSX and omit any cpu/gpu binding?

**Comment by manopapad** [comment]
There is no command line tool on MacOs to do core binding, so I think all we can do is skip binding on MacOS. We could just make the binding script `bind.sh` print a warning if `numactl` isn't available, and just run the application w/o binding (instead of crashing as it does now).

**Comment by bryevdv** [comment]
@manopapad But we need to go back to setting `REALM_SYNTHETIC_CORE_MAP` as before, no? If so I think platform specific test stages are what will work best, since that's exactly the sort of config they encapsulate

**Comment by manopapad** [comment]
> But we need to go back to setting REALM_SYNTHETIC_CORE_MAP as before, no?

Technically yes, but I don't think it matters on MacOS, since Realm can't pin thread on cores on Mac anyway (so it's like REALM_SYNTHETIC_CORE_MAP is set by default on Mac).

**Comment by manopapad** [comment]
We ended up doing both (`test.py` won't try binding at all on Mac, and `bind.sh` will just emit a warning if `numactl` is not found).
