### ISSUE TITLE
cunumeric incompatiblity in slicing

### ISSUE THREAD

**Issue by rohany** [nv-legate/cunumeric#561]
The following code crashes in cunumeric but not numpy.
```
import cunumeric as cn
x = cn.zeros(10)
x[10:10]
```

```
➜  legate.sparse git:(parallel-dia-to-csr) ✗ ../install/bin/legate repro.py -cunumeric:test                                                                                 (legate) 15:29:40
[0 - 117a5ddc0]    0.002973 {4}{threads}: reservation ('CPU proc 1d00000000000003') cannot be satisfied
[0 - 70000a9d6000]    1.505572 {6}{python}: python exception occurred within task:
Traceback (most recent call last):
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/legion_top.py", line 440, in legion_python_main
    run_path(args[start], run_name='__main__')
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/legion_top.py", line 255, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "repro.py", line 4, in <module>
    x[10:10]
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/coverage.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/array.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/array.py", line 939, in __getitem__
    return ndarray(shape=None, thunk=self._thunk.get_item(key))
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/deferred.py", line 800, in get_item
    result = self._get_view(key)
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/cunumeric/deferred.py", line 707, in _get_view
    store = store.slice(dim + shift, k)
  File "/Users/rohany/Documents/nvidia/install/lib/python3.9/site-packages/legate/core/store.py", line 1177, in slice
    raise ValueError(
ValueError: Out-of-bounds slicing slice(10, 10, None) on dimension 0 for a store of shape Shape((10,))
```

**Comment by magnatelee** [comment]
@rohany this seems fixed already. can you confirm the fix and close this issue?

**Comment by rohany** [comment]
Yup, seems fixed.
