### ISSUE TITLE
unique returns incorrect values on GPUs with LEGATE_TEST

### ISSUE THREAD

**Issue by rohany** [nv-legate/cunumeric#684]
The following cunumeric code results in a crash:
```
import cunumeric as np

def stencil_grid(S, grid, dtype=None, format=None):
    N_v = int(np.prod(grid))  # number of vertices in the mesh
    N_s = int((S != 0).sum())  # number of nonzero stencil entries

    # diagonal offsets
    diags = np.zeros(N_s, dtype=int)

    # compute index offset of each dof within the stencil
    strides = np.cumprod([1] + list(reversed(grid)))[:-1]
    indices = tuple(i.copy() for i in S.nonzero())
    for i, s in zip(indices, S.shape):
        i -= s // 2

    for stride, coords in zip(strides, reversed(indices)):
        diags += stride * coords

    data = np.repeat(S[S != 0], N_v).reshape((N_s, N_v))

    indices = np.vstack(indices).T

    # zero boundary connections
    for index, diag in zip(indices, data):
        diag = diag.reshape(grid)
        for n, i in enumerate(index):
            if i > 0:
                s = [slice(None)] * len(grid)
                s[n] = slice(0, i)
                s = tuple(s)
                diag[s] = 0
            elif i < 0:
                s = [slice(None)] * len(grid)
                s[n] = slice(i, None)
                s = tuple(s)
                diag[s] = 0

    # remove diagonals that lie outside matrix
    mask = abs(diags) < N_v
    if not mask.all():
        diags = diags[mask]
        data = data[mask]

    # sum duplicate diagonals
    if len(np.unique(diags)) != len(diags):
        new_diags = np.unique(diags)
        new_data = np.zeros((len(new_diags), data.shape[1]), dtype=data.dtype)

        for dia, dat in zip(diags, data):
            n = np.searchsorted(new_diags, dia)
            new_data[n, :] += dat

        diags = new_diags
        data = new_data


def diffusion2D(N, epsilon=1.0, theta=0.0):
    eps = float(epsilon)  # for brevity
    theta = float(theta)

    C = np.cos(theta)
    S = np.sin(theta)
    CS = C * S
    CC = C**2
    SS = S**2

    a = (-1 * eps - 1) * CC + (-1 * eps - 1) * SS + (3 * eps - 3) * CS
    b = (2 * eps - 4) * CC + (-4 * eps + 2) * SS
    c = (-1 * eps - 1) * CC + (-1 * eps - 1) * SS + (-3 * eps + 3) * CS
    d = (-4 * eps + 2) * CC + (2 * eps - 4) * SS
    e = (8 * eps + 8) * CC + (8 * eps + 8) * SS

    stencil = np.array([[a, b, c], [d, e, d], [c, b, a]]) / 6.0
    return stencil_grid(stencil, (N, N))


if __name__ == "__main__":
    np.random.seed(123)
    num_nodes = 64
    A = diffusion2D(num_nodes, epsilon=0.1, theta=np.pi / 4)
```

when I run it with `LEGATE_TEST=1` and `--gpus 1` it crashes with:
```
[0 - 7f0e45823000]    2.973925 {6}{python}: python exception occurred within task:
Traceback (most recent call last):
  File "/home/rohany/nvidia-2/legate.core/legion/bindings/python/build/lib/legion_top.py", line 446, in legion_python_main
    run_path(args[start], run_name='__main__')
  File "/home/rohany/nvidia-2/legate.core/legion/bindings/python/build/lib/legion_top.py", line 255, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "repro.py", line 81, in <module>
    A = diffusion2D(num_nodes, epsilon=0.1, theta=np.pi / 4).tocsr()
  File "repro.py", line 75, in diffusion2D
    return stencil_grid(stencil, (N, N))
  File "repro.py", line 52, in stencil_grid
    new_data[n, :] += dat
  File "/home/rohany/nvidia-2/legate.core/legate/core/context.py", line 241, in wrapper
    result = func(*args, **kwargs)
  File "/home/rohany/nvidia-2/cunumeric/cunumeric/coverage.py", line 113, in wrapper
    return func(*args, **kwargs)
  File "/home/rohany/nvidia-2/cunumeric/cunumeric/array.py", line 144, in wrapper
    return func(*args, **kwargs)
  File "/home/rohany/nvidia-2/cunumeric/cunumeric/array.py", line 936, in __getitem__
    return ndarray(shape=None, thunk=self._thunk.get_item(key))
  File "/home/rohany/nvidia-2/cunumeric/cunumeric/eager.py", line 416, in get_item
    out = self.array[index_key]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

when I run it without `LEGATE_TEST=1` or without GPUs and `LEGATE_TEST=1` it succeeds.

cc @ipdemes

**Comment by manopapad** [comment]
I added some logging to your program right before the crash, and it looks like it's trying to do something illegal:
```
trying to execute new_data[n, :] where new_data.shape = (0, 4096), n.shape = (), n = 0
```
Is this right?

**Comment by rohany** [comment]
I don't think that there's an error in the code itself, it works with both normal numpy and CPUs.

**Comment by rohany** [comment]
> I added some logging to your program right before the crash, and it looks like it's trying to do something illegal:

It must be that something else is going wrong here when `--gpus 1` is on as the code doesn't enter that branch otherwise. Let me try to minimize more.

**Comment by rohany** [comment]
Ok, here's the problem:

```
(legate-2) rohany@g0002:~/nvidia-2/legate.sparse$ cat repro2.py
import cunumeric as np
x = np.array([-65, -64, -63,  -1,   0,   1,  63 , 64 , 65])
print(np.unique(x))
(legate-2) rohany@g0002:~/nvidia-2/legate.sparse$ LEGATE_TEST=1 LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH legate repro2.py --gpus 1 --launcher mpirun
[]
(legate-2) rohany@g0002:~/nvidia-2/legate.sparse$ LEGATE_TEST=1 LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH legate repro2.py --cpus 1 --launcher mpirun
[-65 -64 -63  -1   0   1  63  64  65]
```

**Comment by rohany** [comment]
https://github.com/nv-legate/cunumeric/blob/branch-22.12/src/cunumeric/set/unique.cu#L171 appears to be the offending line, as `end` shouldn't be shadowed here. Changing this fixes the bug for me, though I don't know what else could be wrong with it (cc @magnatelee for the git blame).
