### ISSUE TITLE
`sort` hangs due to stuck NCCL kernels in sort on 48GPUs on Summit

### ISSUE THREAD

**Issue by rohany** [nv-legate/cunumeric#722]
The following reproducer:
```
import cunumeric as np

class dia_array:
    def __init__(self, arg, shape=None, copy=False):
        assert isinstance(arg, tuple)
        data, offsets = arg
        if isinstance(offsets, int):
            offsets = np.full((1,), offsets)

        self.shape = tuple(int(i) for i in shape)
        self.offsets = offsets
        self.data = data

    def tocoo(self, copy=False):
        if copy:
            return self.copy().tocoo(copy=False)
        num_rows, num_cols = self.shape
        num_offsets, offset_len = self.data.shape
        offset_inds = np.arange(offset_len)

        row = offset_inds - self.offsets[:, None]
        mask = row >= 0
        mask &= row < num_rows
        mask &= offset_inds < num_cols
        mask &= self.data != 0
        row = np.array(row[mask])
        col = np.array(
            np.tile(offset_inds, num_offsets)[mask.ravel()]
        )
        data = np.array(self.data[mask])

        return (data, row, col)


def stencil_grid(S, grid, dtype=None, format=None):
    N_v = int(np.prod(grid))  # number of vertices in the mesh
    N_s = int((S != 0).sum())  # number of nonzero stencil entries

    # diagonal offsets
    diags = np.zeros(N_s, dtype=int)

    # compute index offset of each dof within the stencil
    strides = np.cumprod([1] + list(reversed(grid)))[:-1]
    indices = tuple(i.copy() for i in S.nonzero())
    for i, s in zip(indices, S.shape):
        i -= s // 2

    for stride, coords in zip(strides, reversed(indices)):
        diags += stride * coords

    data = np.repeat(S[S != 0], N_v).reshape((N_s, N_v))

    indices = np.vstack(indices).T

    # zero boundary connections
    for index, diag in zip(indices, data):
        diag = diag.reshape(grid)
        for n, i in enumerate(index):
            if i > 0:
                s = [slice(None)] * len(grid)
                s[n] = slice(0, i)
                s = tuple(s)
                diag[s] = 0
            elif i < 0:
                s = [slice(None)] * len(grid)
                s[n] = slice(i, None)
                s = tuple(s)
                diag[s] = 0

    # remove diagonals that lie outside matrix
    mask = abs(diags) < N_v
    if not mask.all():
        diags = diags[mask]
        data = data[mask]

    # sum duplicate diagonals
    if len(np.unique(diags)) != len(diags):
        new_diags = np.unique(diags)
        new_data = np.zeros((len(new_diags), data.shape[1]), dtype=data.dtype)

        for dia, dat in zip(diags, data):
            n = np.searchsorted(new_diags, dia)
            new_data[n, :] += dat

        diags = new_diags
        data = new_data

    return dia_array((data, diags), shape=(N_v, N_v))


def poisson2D(N):
    M = 2
    stencil = np.zeros((3,) * M, dtype=float)
    for i in range(M):
        stencil[(1,) * i + (0,) + (1,) * (M - i - 1)] = -1
        stencil[(1,) * i + (2,) + (1,) * (M - i - 1)] = -1
    stencil[(1,) * M] = 2 * M
    return stencil_grid(stencil, (N, N))


if __name__ == "__main__":
    np.random.seed(123)
    print("Starting up!")
    num_nodes = 10392
    (data, row, col) = poisson2D(num_nodes).tocoo()

    print("Before sort")
    np.sort(data).shape
    print("After sort")
```

Run as `LEGATE_TEST=1 PYTHONUNBUFFERED=1 LD_LIBRARY_PATH=$CONDA_PREFIX/lib:$LD_LIBRARY_PATH legate hang-repro.py --fbmem 13000 --zcmem 10000 --sysmem 50000 -cunumeric:preload-cudalibs --eager-alloc-percentage 40 --gpus 6 --cpus 6 --nodes 8 --launcher jsrun --launcher-extra="--smpiargs='off'"` on Summit will hang and not print `"After sort"`. Seeing the threads on each node will show that every GPU task thread is stuck in:
```
Thread 43 (Thread 0x2001bc21f890 (LWP 1831194)):
#0  0x0000200007f75a60 in do_futex_wait.constprop () from /lib64/power9/libpthread.so.0
#1  0x0000200007f75c18 in __new_sem_wait_slow.constprop.0 () from /lib64/power9/libpthread.so.0
#2  0x0000200006e43e70 in ?? () from /lib64/libcuda.so.1
#3  0x0000200006cfb20c in ?? () from /lib64/libcuda.so.1
#4  0x0000200006f99940 in ?? () from /lib64/libcuda.so.1
#5  0x0000200006e1abe4 in ?? () from /lib64/libcuda.so.1
#6  0x0000200006e1ae2c in ?? () from /lib64/libcuda.so.1
#7  0x0000200006cde9d4 in ?? () from /lib64/libcuda.so.1
#8  0x0000200006f2b40c in cuStreamSynchronize () from /lib64/libcuda.so.1
#9  0x000020000413f4d0 in ?? () from /sw/summit/cuda/11.0.2/lib64/libcudart.so.11.0
#10 0x000020000419deb8 in cudaStreamSynchronize () from /sw/summit/cuda/11.0.2/lib64/libcudart.so.11.0
#11 0x00002000eee38a1c in double* thrust::cuda_cub::merge<thrust::detail::execute_with_allocator<cunumeric::ThrustAllocator&, thrust::cuda_cub::execute_on_stream_base>, double*, double*, double*, thrust::less<double> >(thrust::cuda_cub::execution_policy<thrust::detail::execute_with_allocator<cunumeric::ThrustAllocator&, thrust::cuda_cub::execute_on_stream_base> >&, double*, double*, double*, double*, double*, thrust::less<double>) () from /autofs/nccs-svm1_home1/rohany/nvidia/cunumeric/build/lib/libcunumeric.so
#12 0x00002000eee52d18 in cunumeric::SegmentMergePiece<legate::LegateTypeOf<(legate_core_type_code_t)11>::type> cunumeric::merge_all_buffers<(legate_core_type_code_t)11>(std::vector<cunumeric::SegmentMergePiece<legate::LegateTypeOf<(legate_core_type_code_t)11>::type>, std::allocator<cunumeric::SegmentMergePiece<legate::LegateTypeOf<(legate_core_type_code_t)11>::type> > >&, bool, bool, cunumeric::ThrustAllocator&, CUstream_st*) () from /autofs/nccs-svm1_home1/rohany/nvidia/cunumeric/build/lib/libcunumeric.so
#13 0x00002000eee94328 in void cunumeric::sample_sort_nccl_nd<(legate_core_type_code_t)11>(cunumeric::SortPiece<legate::LegateTypeOf<(legate_core_type_code_t)11>::type>, legate::Store&, void*, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, unsigned long*, unsigned long, bool, bool, CUstream_st*, ncclComm**) ()
   from /autofs/nccs-svm1_home1/rohany/nvidia/cunumeric/build/lib/libcunumeric.so
#14 0x00002000eee94f6c in cunumeric::SortImplBody<(cunumeric::VariantKind)2, (legate_core_type_code_t)11, 1>::operator()(legate::Store const&, legate::Store&, cunumeric::Pitches<0, true> const&, Realm::Rect<1, long long> const&, unsigned long, unsigned long, unsigned long, bool, bool, bool, unsigned long, unsigned long, unsigned long, std::vector<legate::comm::Communicator, std::allocator<legate::comm::Communicator> > const&) () from /autofs/nccs-svm1_home1/rohany/nvidia/cunumeric/build/lib/libcunumeric.so
#15 0x00002000eee9f550 in decltype(auto) legate::inner_type_dispatch_fn<1>::operator()<cunumeric::SortImpl<(cunumeric::VariantKind)2>, cunumeric::SortArgs&, std::vector<legate::comm::Communicator, std::allocator<legate::comm::Communicator> >&>(legate_core_type_code_t, cunumeric::SortImpl<(cunumeric::VariantKind)2>, cunumeric::SortArgs&, std::vector<legate::comm::Communicator, std::allocator<legate::comm::Communicator> >&) () from /autofs/nccs-svm1_home1/rohany/nvidia/cunumeric/build/lib/libcunumeric.so
#16 0x00002000eedef2b0 in void cunumeric::sort_template<(cunumeric::VariantKind)2>(legate::TaskContext&) () from /autofs/nccs-svm1_home1/rohany/nvidia/cunumeric/build/lib/libcunumeric.so
#17 0x00002000eecb6e5c in void legate::LegateTask<cunumeric::SortTask>::legate_task_wrapper<&cunumeric::SortTask::gpu_variant>(void const*, unsigned long, void const*, unsigned long, Realm::Processor) () from /autofs/nccs-svm1_home1/rohany/nvidia/cunumeric/build/lib/libcunumeric.so
#18 0x0000200005165fe4 in Realm::LocalTaskProcessor::execute_task (this=0x3d36c3c0, func_id=1173, task_args=...) at /autofs/nccs-svm1_home1/rohany/nvidia/legate.core/legion/runtime/realm/proc_impl.cc:1135
#19 0x000020000520c22c in Realm::Task::execute_on_processor (this=0x2000600b8c00, p=...) at /autofs/nccs-svm1_home1/rohany/nvidia/legate.core/legion/runtime/realm/tasks.cc:302
#20 0x00002000052112c4 in Realm::KernelThreadTaskScheduler::execute_task (this=0x409f9670, task=0x2000600b8c00) at /autofs/nccs-svm1_home1/rohany/nvidia/legate.core/legion/runtime/realm/tasks.cc:1366
#21 0x0000200005293f90 in Realm::Cuda::GPUTaskScheduler<Realm::KernelThreadTaskScheduler>::execute_task (this=0x409f9670, task=0x2000600b8c00) at /autofs/nccs-svm1_home1/rohany/nvidia/legate.core/legion/runtime/realm/cuda/cuda_module.cc:1568
#22 0x000020000520fcf0 in Realm::ThreadedTaskScheduler::scheduler_loop (this=0x409f9670) at /autofs/nccs-svm1_home1/rohany/nvidia/legate.core/legion/runtime/realm/tasks.cc:1105
#23 0x00002000052103e8 in Realm::ThreadedTaskScheduler::scheduler_loop_wlock (this=0x409f9670) at /autofs/nccs-svm1_home1/rohany/nvidia/legate.core/legion/runtime/realm/tasks.cc:1217
```

I'm on the `collective` branch of Legion, though I doubt the bug has anything to do with that.

**Comment by rohany** [comment]
Turns out this was caused by not guarding calls to NCCL sends with 0 checks.
