### ISSUE TITLE
legate/cunumeric should skip gpus that are not volta+ or give a reasonable error message. 

### ISSUE THREAD

**Issue by mag1cp1n** [nv-legate/cunumeric#862]
I have 2 boards on my Ubuntu system (GM206 and TU104). 

I observed that **if I pass both the gpus to the docker:**
_sudo docker run -i --rm --runtime=nvidia --gpus **all** -t cunumeric:_
I get below error while running the test--
 (legate) root@757e800e1646:/app/cunumeric# ./test.py --use cuda,cpus
 Traceback (most recent call last):
 File "/app/cunumeric/./test.py", line 47, in <module>
   plan = TestPlan(config, system)
 File "/root/miniconda3/envs/legate/lib/python3.10/site-packages/legate/tester/test_plan.py", line 47, in __init__
   self._stages = [
 File "/root/miniconda3/envs/legate/lib/python3.10/site-packages/legate/tester/test_plan.py", line 48, in <listcomp>
   STAGES[feature](config, system) for feature in config.features
 File "/root/miniconda3/envs/legate/lib/python3.10/site-packages/legate/tester/stages/_linux/gpu.py", line 50, in __init__
   self._init(config, system)
 File "/root/miniconda3/envs/legate/lib/python3.10/site-packages/legate/tester/stages/test_stage.py", line 285, in _init
   self.spec = self.compute_spec(config, system)
 File "/root/miniconda3/envs/legate/lib/python3.10/site-packages/legate/tester/stages/_linux/gpu.py", line 74, in compute_spec
   workers = adjust_workers(
 File "/root/miniconda3/envs/legate/lib/python3.10/site-packages/legate/tester/stages/util.py", line 106, in adjust_workers
   raise RuntimeError("Current configuration results in zero workers")
 RuntimeError: Current configuration results in zero workers
 
 **If I pass TU104 device to the docker, the test succeeds.**
 _sudo docker run -i --rm --runtime=nvidia --gpus **'"device=1"'** -t cunumeric_
 
 As I understand from Mark, the legate/cunumeric should skip the maxwell or give a reasonable error message saying it only supports volta+

**Comment by magnatelee** [comment]
Cc @bryevdv. this looks like an issue in the test driver. @mag1cp1n is the framebuffer smaller than 6GB? that could cause the test driver to fail to create a worker, as the default budget is 6GB. can you try with `--fbmem 1024 -j 1` and see if that gives you a different behavior?

**Comment by mag1cp1n** [comment]
- GM 206 is 2GB.
- Tried with ./test.py **--fbmem 1024 -j 1**  --use cuda,cpus
   I don't see the earlier error.
   Below is the Test config and end summary I get:

################################################################################
###
### Test Suite Configuration
###
### * Feature stages       : cpus, cuda
### * Test files per stage : 135
### * TestSystem description   : 6 cpus / **2 gpus**
###
################################################################################
   ################################################################################
###
### Overall summary
###
### * CPU   : 135 / 135 passed in 533.63s
### * GPU   : 90 / 135 passed in 784.42s
###
### All tests: Passed 225 of 270 tests (83.3%) in 1318.05s
###
################################################################################
