### ISSUE TITLE
cuNumeric ndarray.tofile is broken

### ISSUE THREAD

**Issue by yimoj** [nv-legate/cunumeric#969]
Cannot use `tofile` to dump an array no matter how the argument is specified.
```
>>> arr.tofile("arr_dump")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yimoj/legate/legate.core/legate/core/runtime.py", line 1889, in wrapper
    result = func(*args, **kwargs)
  File "/home/yimoj/legate/cunumeric/cunumeric/coverage.py", line 119, in wrapper
    return func(*args, **kwargs)
  File "/home/yimoj/legate/cunumeric/cunumeric/array.py", line 3631, in tofile
    return self.__array__().tofile(fid=fid, sep=sep, format=format)
TypeError: tofile() missing required argument 'file' (pos 1)
```

```
>>> arr.tofile(file="arr_dump")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yimoj/legate/legate.core/legate/core/runtime.py", line 1892, in wrapper
    result = func(*args, **kwargs)
  File "/home/yimoj/legate/cunumeric/cunumeric/coverage.py", line 119, in wrapper
    return func(*args, **kwargs)
TypeError: ndarray.tofile() got an unexpected keyword argument 'file'
```

```
>>> arr.tofile(fid="arr_dump")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yimoj/legate/legate.core/legate/core/runtime.py", line 1892, in wrapper
    result = func(*args, **kwargs)
  File "/home/yimoj/legate/cunumeric/cunumeric/coverage.py", line 119, in wrapper
    return func(*args, **kwargs)
  File "/home/yimoj/legate/cunumeric/cunumeric/array.py", line 3631, in tofile
    return self.__array__().tofile(fid=fid, sep=sep, format=format)
TypeError: tofile() missing required argument 'file' (pos 1)
```

**Comment by yimoj** [comment]
Fixed.
```
>>> num.array([1,2,3]).tofile("test_num")
>>> with open("test_num", "rb") as f:
...     f.readlines()
...
[b'\x01\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00']
```
